-- Phase 7b: per-slot personality + dialogue lines, generated by Gemini from
-- each slot's own top artist names (worker/persona.ts) and cached here so a
-- slot only ever costs a fresh Gemini call when its top-artist set actually
-- changes — and even then, at most once a day (see worker/persona.ts's
-- REGEN_INTERVAL_MS). Its own new table, not a column added to artist_cache
-- (that table is keyed by artist, this is keyed by slot) — purely additive,
-- no existing table changed.

CREATE TABLE slot_persona (
  slot_id TEXT PRIMARY KEY,
  -- Empty string + "[]" marks a row written after a Gemini attempt produced
  -- nothing usable (worker/persona.ts's EMPTY_PERSONA) rather than a real
  -- persona — read back as null, never shown, only there to carry the
  -- fingerprint/timestamp below so that slot isn't retried on every build.
  personality TEXT NOT NULL, -- short in-character blurb, 1-2 sentences
  dialogue TEXT NOT NULL, -- JSON array of ~4-6 short in-character lines
  -- The top artist names (lowercased, pipe-joined, see worker/persona.ts's
  -- fingerprint() — built from the range-independent long_term baseline, not
  -- whichever era a visitor is viewing) this row was last generated/attempted
  -- from. Compared against the slot's current fingerprint on every village
  -- build; a mismatch is what makes this row eligible for regeneration
  -- (subject to generated_at's once/day cap).
  artist_fingerprint TEXT NOT NULL,
  generated_at TEXT NOT NULL -- ISO timestamp of the last generation or attempt
);
