-- Phase 9: the weekly notice board. One row per owner-local week (Monday
-- start, wrangler.jsonc's OWNER_TZ var — see worker/weekly-brief.ts), holding
-- a Gemini-narrated headline/notes plus the per-slot lines the sidebar's
-- "This week" section reads. Generated by the existing 15-min cron
-- (worker/index.ts's scheduled(), right after worker/history.ts's sync) —
-- no new cron trigger. Purely additive — no existing table touched.

CREATE TABLE weekly_brief (
  week_start TEXT PRIMARY KEY, -- owner-local Monday, "YYYY-MM-DD"
  -- 'pending' rows are stats-only: a real Gemini attempt was made and either
  -- failed or hit today's quota, and this week is eligible for a retry on a
  -- later cron tick (worker/weekly-brief.ts's RETRY_COOLDOWN_MS gates how
  -- soon) — headline/notes/slot_notes are "" / "[]" / "{}" until a retry
  -- succeeds. 'ready' rows are done for good and are all GET
  -- /api/weekly-brief ever returns — whether Gemini actually wrote them or
  -- the week was too thin for a Gemini call at all (see MIN_WEEK_PLAYS).
  status TEXT NOT NULL, -- 'ready' | 'pending'
  headline TEXT NOT NULL,
  notes TEXT NOT NULL, -- JSON array of a few short global observations
  slot_notes TEXT NOT NULL, -- JSON object: slot id -> one short line
  -- What the brief (or the pending attempt) was generated from — ids and
  -- derived counts only, never raw Spotify content (SPEC.md's storage
  -- policy): per-slot play counts this week vs the week before, and this
  -- week's brand-new (never-played-before) artists by id + play count.
  -- Artist/slot names are never duplicated in here — always joined from
  -- artist_cache at read time, same convention as every other derived table
  -- in this Worker (play_event, etc.).
  stats TEXT NOT NULL,
  generated_at TEXT NOT NULL, -- ISO timestamp of this row's most recent write
  last_attempt_at TEXT NOT NULL -- ISO timestamp of the most recent generation attempt, success or not
);
