// Echoes Worker — serves the Vite build as static assets and exposes a
// small API surface. Phase 2 adds the Spotify token manager (token.ts), the
// rate-aware fetch wrapper (spotify-fetch.ts), and /api/top-artists
// (top-artists.ts). Phase 3 adds /api/village (village.ts, genre resolution
// via Gemini) and per-IP rate limiting (rate-limit.ts), applied here to
// every /api/* route before it's dispatched. Phase 3.5 adds real top tracks
// to /api/village (worker/tracks.ts). Its CSP (the sidebar now hotlinks
// Spotify album art) lives in public/_headers, not here — wrangler.jsonc's
// `assets` config has no `run_worker_first`, so a request for "/" is served
// straight off Cloudflare's static-asset layer without this fetch handler
// running at all; a header set here on env.ASSETS.fetch()'s result would be
// dead code for exactly the response it needs to reach (fix pass, 2026-09-17
// — a first attempt tried exactly that and it silently never fired). Phase
// 5a adds /api/now-playing (now-playing.ts) for the display-only now-playing
// card. Phase 8a adds a `scheduled()` export (wrangler.jsonc's
// `triggers.crons`) driving worker/history.ts's play-event log, plus
// /api/history/stats for its small frontend readout. Phase 8b adds
// /api/history/daily (history-daily.ts) for the sidebar's per-district
// 30-day strip. Phase 8.5 adds /api/wrapped (wrapped.ts) for the sidebar's
// Wrapped tab — an on-demand read over play_event, falling back to Spotify's
// own top lists when a range's history is too thin. Phase 8.6 (first cut)
// adds /api/playlists + /api/playlists/{id} (playlists.ts) for the
// sidebar's Playlists tab — see SPEC.md's Phase 8.6 note for what's deferred.
// Phase 9 adds /api/weekly-brief (weekly-brief.ts) for the notice board +
// sidebar "This week" section, generated by that file's own runWeeklyBrief
// riding this same scheduled() tick, right after the history sync. Phase 10
// adds POST /api/hokage (hokage.ts) — this Worker's first POST route, the
// chat UI's Gemini-function-calling backend. Phase 11 adds GET /api/world +
// POST /api/world/run (village-agent.ts) for the daily village-evolution
// agent, generated by that file's own runVillageAgent riding this same
// scheduled() tick, right after the weekly brief. Phase 12 adds GET
// /api/chronicle (chronicle.ts) — a read-only timeline of what that agent
// did each day, plus per-day state for the sidebar's replay; D1-only, no
// Spotify/Gemini call this route can ever trigger.

import { handleTopArtists } from "./top-artists";
import { handleVillage } from "./village";
import { handleNowPlaying } from "./now-playing";
import { runHistorySync, handleHistoryStats } from "./history";
import { handleHistoryDaily } from "./history-daily";
import { handleHistoryHourly } from "./history-hourly";
import { handleWrapped } from "./wrapped";
import { handlePlaylists, handlePlaylistDetail } from "./playlists";
import { runWeeklyBrief, handleWeeklyBrief } from "./weekly-brief";
import { handleHokage } from "./hokage";
import { runVillageAgent, handleGetWorld, handleRunWorld } from "./village-agent";
import { handleChronicle } from "./chronicle";
import { clientIp, enforceRateLimit, RateLimitError, RATE_LIMIT_RULES } from "./rate-limit";

export interface Env {
  ASSETS: Fetcher;
  DB: D1Database;
  /** Public PKCE client id (no client secret exists) — set in wrangler.jsonc's `vars`. */
  SPOTIFY_CLIENT_ID: string;
  /** Base64 AES-256 key encrypting the stored refresh token — a Worker secret (`wrangler secret put TOKEN_KEY`). */
  TOKEN_KEY: string;
  /** Gemini API key (free tier) — a Worker secret (`wrangler secret put GEMINI_API_KEY`). Used only by worker/gemini.ts. */
  GEMINI_API_KEY: string;
  /** The one owner's IANA timezone (wrangler.jsonc's `vars`) — worker/history-daily.ts buckets
   * /api/history/daily's 30-day strip into their local calendar days, not each visitor's. */
  OWNER_TZ: string;
  /** Phase 11: shared secret gating POST /api/world/run (worker/village-agent.ts) — a Worker
   * secret (`wrangler secret put AGENT_TRIGGER_TOKEN`), optional (the route 404s when unset). */
  AGENT_TRIGGER_TOKEN?: string;
}

/** Maps a route to its rate-limit bucket — every /api/* route is limited
 * (SPEC.md's "Hosting"); /api/village is stricter since it's the only one
 * that can trigger a Gemini call (its own daily cap is separate, see
 * rate-limit.ts's geminiQuotaAvailable). */
const ROUTE_BUCKETS: Record<string, keyof typeof RATE_LIMIT_RULES> = {
  "/api/health": "health",
  "/api/top-artists": "topArtists",
  "/api/village": "village",
  "/api/now-playing": "nowPlaying",
  "/api/history/stats": "historyStats",
  // D1-only reads too (worker/history-daily.ts) — same generous limit as
  // historyStats, reusing its rule rather than defining a near-identical one.
  "/api/history/daily": "historyStats",
  // Time-lapse's 24h-hourly read (worker/history-hourly.ts) — same D1-only
  // profile as /api/history/daily above, so it reuses that bucket too.
  "/api/history/hourly": "historyStats",
  // Phase 8.5: the common case is D1-only, same as /api/history/daily above.
  // When it does fall back to Spotify (worker/wrapped.ts), that fallback is
  // itself cached in caches.default by time_range (same 30-min-TTL
  // convention as worker/top-artists.ts) — that cache, not this per-IP
  // bucket, is what actually keeps a burst of visitors from burning the
  // Spotify quota. This bucket is just abuse protection on top, same role
  // it plays for every other route here.
  "/api/wrapped": "historyStats",
  // Phase 8.6: the list endpoint. /api/playlists/{id} isn't a fixed
  // pathname (see PLAYLIST_DETAIL_RE below), so it's matched separately in
  // fetch() rather than living in this exact-match table.
  "/api/playlists": "playlists",
  // Phase 9: D1-only read of one precomputed row (worker/weekly-brief.ts) —
  // no Spotify or Gemini call this route can ever trigger (generation is the
  // cron's job), so it reuses historyStats' generous limit, same as
  // /api/history/daily and /api/wrapped's common case above.
  "/api/weekly-brief": "historyStats",
  // Phase 10: POST /api/hokage can trigger up to 5 Gemini calls per request
  // (worker/gemini.ts's chatWithTools: MAX_CHAT_STEPS tool-enabled steps
  // plus one possible forced final turn) — its own dedicated, tighter bucket.
  // The real daily cost ceiling is worker/hokage.ts's own per-IP question
  // cap (enforced in the handler, not here — see that file's doc comment on
  // why this generic fail-open bucket isn't enough on its own).
  "/api/hokage": "hokage",
  // Phase 11: GET /api/world (worker/village-agent.ts) — D1-only reads, same
  // generous limit as historyStats/weeklyBrief above.
  "/api/world": "world",
  // Phase 11: POST /api/world/run — token-gated manual trigger for the daily
  // village agent, its own tighter bucket (see rate-limit.ts's doc comment).
  "/api/world/run": "worldRun",
  // Phase 12: GET /api/chronicle (worker/chronicle.ts) — D1-only reads of
  // agent_run/agent_event, no Spotify/Gemini call this route can ever
  // trigger, same profile as /api/world above, so it reuses that bucket
  // rather than defining a near-identical one.
  "/api/chronicle": "world",
};

// Phase 8.6: GET /api/playlists/{id} — the one route in this Worker with a
// path parameter, so it can't live in ROUTE_BUCKETS' exact-pathname lookup
// above. Matched before ROUTE_BUCKETS in fetch() below.
const PLAYLIST_DETAIL_RE = /^\/api\/playlists\/([^/]+)$/;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const playlistDetailMatch = url.pathname.match(PLAYLIST_DETAIL_RE);
    const bucket = playlistDetailMatch ? "playlistDetail" : ROUTE_BUCKETS[url.pathname];

    if (bucket) {
      try {
        await enforceRateLimit(env, clientIp(request), bucket, RATE_LIMIT_RULES[bucket]);
      } catch (err) {
        if (err instanceof RateLimitError) {
          return Response.json(
            { error: "Too many requests" },
            { status: 429, headers: { "Retry-After": String(err.retryAfterSeconds) } },
          );
        }
        // Rate limiting itself is abuse protection, not core functionality —
        // if its D1 counter fails for some unrelated reason, fail *open*
        // (let the request through) rather than 500ing every route.
        console.error(`[rate-limit] enforcement failed for ${bucket}, failing open:`, err);
      }
    }

    if (url.pathname === "/api/health") {
      return Response.json({ ok: true });
    }

    if (url.pathname === "/api/top-artists") {
      return handleTopArtists(request, env);
    }

    if (url.pathname === "/api/village") {
      return handleVillage(request, env);
    }

    if (url.pathname === "/api/now-playing") {
      return handleNowPlaying(env);
    }

    if (url.pathname === "/api/history/stats") {
      return handleHistoryStats(env);
    }

    if (url.pathname === "/api/history/daily") {
      return handleHistoryDaily(env);
    }

    if (url.pathname === "/api/history/hourly") {
      return handleHistoryHourly(env);
    }

    if (url.pathname === "/api/wrapped") {
      return handleWrapped(request, env);
    }

    if (url.pathname === "/api/playlists") {
      return handlePlaylists(env);
    }

    if (url.pathname === "/api/weekly-brief") {
      return handleWeeklyBrief(env);
    }

    if (url.pathname === "/api/hokage") {
      return handleHokage(request, env);
    }

    if (url.pathname === "/api/world") {
      return handleGetWorld(env);
    }

    if (url.pathname === "/api/world/run") {
      return handleRunWorld(request, env);
    }

    if (url.pathname === "/api/chronicle") {
      return handleChronicle(env);
    }

    if (playlistDetailMatch) {
      // The raw path segment, undecoded — worker/playlists.ts shape-checks
      // it against Spotify's base62 id format before using it for anything,
      // so decoding here would only add a URIError-on-malformed-%-escape
      // failure mode (500, e.g. a request for /api/playlists/%zz) for no
      // benefit.
      return handlePlaylistDetail(request, env, playlistDetailMatch[1]!);
    }

    // Reached only when a request matches neither a rate-limited /api/*
    // route above nor a real static file (those are served directly off
    // Cloudflare's asset layer without invoking this handler at all) — i.e.
    // effectively just the "asset not found" fallthrough. See public/_headers
    // for the CSP that used to be (incorrectly) applied here.
    return env.ASSETS.fetch(request);
  },

  // Phase 8a: 15-min play-event log (wrangler.jsonc's `triggers.crons`).
  // `runHistorySync` never throws (every failure path logs a `history_sync`
  // row and returns instead) — `waitUntil` just makes sure the isolate stays
  // alive until its D1 writes land rather than being torn down the instant
  // this handler returns. Phase 9's `runWeeklyBrief` (also never throws)
  // rides the same tick, after history sync so it sees this run's freshest
  // plays — see its own doc comment for the once-a-week generation gate.
  // Phase 11's `runVillageAgent` (also never throws) rides the same tick
  // again, after the weekly brief — see its own doc comment for the
  // once-a-day generation gate.
  async scheduled(_controller, env, ctx) {
    ctx.waitUntil(runHistorySync(env).then(() => runWeeklyBrief(env)).then(() => runVillageAgent(env)));
  },
} satisfies ExportedHandler<Env>;
